# Generated by Django 3.2.10 on 2021-12-13 15:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор записи')),
                ('text', models.TextField(blank=True, verbose_name='Текс записи')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата редактирования')),
                ('closed_at', models.DateTimeField(null=True, verbose_name='Дата закрытия')),
                ('done', models.BooleanField(default=False, verbose_name='Выполнено ли')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
